
export const REPORTS_SELECTED_BRANCH = "REPORTS_SELECTED_BRANCH";
export const VIEW_REPORT_DATA = "VIEW_REPORT_DATA";
export const FINANCIAL_INFO = "FINANCIAL_INFO";
export const DELETE_REPORT_UNSOLD = "DELETE_REPORT_UNSOLD";
