export const USERS_LIST = 'USERS_LIST';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_PERMISSION_USER = 'SET_PERMISSION_USER';
export const DESIGNATION_LIST = 'DESIGNATION_LIST';
export const SELECTED_USER_PERMISSION = 'SELECTED_USER_PERMISSION';
export const ACTIVE_USER_IN_PERMISSION = 'ACTIVE_USER_IN_PERMISSION';
export const EDIT_USER_INFO = 'EDIT_USER_INFO';